### ISSUE TITLE
SettingOptions missing constructor

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/VU-Docs#100]
https://docs.veniceunleashed.net/vext/ref/client/type/settingoptions/
should be this instead:
```yaml
name: SettingOptions
type: class

constructors:
  -

properties:
  displayName:
    type: string
  showInUi:
    type: bool
```
